server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.193:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

logging:
  config: classpath:logback-spring.xml



